name: Python SonarQube Analysis

on: [push]

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install SonarQube Scanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
        unzip sonar-scanner-cli-4.6.0.2311-linux.zip
        export PATH="$PATH:$PWD/sonar-scanner-cli-4.6.0.2311-linux/bin"
    
    - name: Check SonarQube Scanner
      run: |
        which sonar-scanner
        echo $PATH
    
    - name: Run SonarQube analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=ManoelRL_SeleniumEngSoft \
          -Dsonar.organization=manoelrl \
          -Dsonar.sources=.

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
